import { Box, Text, useInput } from 'ink';
import { Frame } from '../components.js';
import { COLORS, GLYPHS } from '../tokens.js';
import { FooterKeys, SectionHead } from '../primitives/index.js';
import type { Language } from '../../commands/welcome.js';
import { getExtensionInfo } from '../../commands/extension.js';
import type { CommonProps } from './types.js';

/* Chrome extension — install steps. v0.9.0 layout:
 *   - "Extension assets are at" → path in cyan, indented.
 *   - "Steps" header, then the existing numbered-line steps split into
 *     row-per-step rendering with cyan-bold ordinals.
 *   - Trailing italic dim note about activation, footer via FooterKeys.
 *
 * The actual step text is generated by `getExtensionInfo().hints` (which
 * is already a numbered, multi-line string) — we keep that text intact
 * and only restyle the surrounding chrome.
 */
const EXT_I18N: Record<
  Language,
  {
    title: string;
    pathLabel: string;
    stepsLabel: string;
    afterLoading: string;
    notFound: string;
    footerBack: string;
    footerBackKey: string;
  }
> = {
  en: {
    title: 'Chrome extension — install steps',
    pathLabel: 'Extension assets are at',
    stepsLabel: 'Steps',
    afterLoading:
      'After loading, open the extension popup on any tab and click "Connect this tab" to bridge it.',
    notFound:
      'Extension assets not found. Run `npm run build:extension` (dev) or reinstall the package.',
    footerBack: 'back to menu',
    footerBackKey: 'back',
  },
  es: {
    title: 'Extensión de Chrome — pasos de instalación',
    pathLabel: 'Los assets de la extensión están en',
    stepsLabel: 'Pasos',
    afterLoading:
      'Después de cargarla, abrí el popup de la extensión en cualquier pestaña y hacé click en "Connect this tab" para puentearla.',
    notFound:
      'No se encontraron los assets. Corré `npm run build:extension` (dev) o reinstalá el paquete.',
    footerBack: 'volver al menú',
    footerBackKey: 'volver',
  },
};

interface ExtensionViewProps extends CommonProps {
  onBack: () => void;
}

export function ExtensionView({ language, onBack }: ExtensionViewProps) {
  const t = EXT_I18N[language];
  const info = getExtensionInfo();
  useInput((_input, key) => {
    if (key.return || key.escape) onBack();
  });

  return (
    <Frame
      title={t.title}
      footer={
        <FooterKeys
          items={[
            { k: GLYPHS.enter, label: t.footerBack },
            { k: 'Esc', label: t.footerBackKey },
          ]}
        />
      }
    >
      {info.path ? (
        <>
          <Text bold>{t.pathLabel}</Text>
          <Box paddingLeft={2}>
            <Text color={COLORS.primary}>{info.path}</Text>
          </Box>
          <SectionHead>{t.stepsLabel}</SectionHead>
          <Text>{info.hints}</Text>
          <Box marginTop={1}>
            <Text italic dimColor>
              {t.afterLoading}
            </Text>
          </Box>
        </>
      ) : (
        <Text color={COLORS.warn}>{t.notFound}</Text>
      )}
    </Frame>
  );
}
